---
  - name: Deploy FES artifact
    hosts: localhost
    gather_facts: true
    collections:
      - ch_collections.base
    vars:
      application_name: "fes"
      home_dir: "/home/fes"
      directories:
        - "data"
        - "supportscripts"
      config_files:
        - "FES"
    roles:
      - { role: /root/roles/nfs_mounts }
      - name: ch_collections.base.cloudwatch_agent_config
        when: cw_log_files is defined
    tasks:
   #   - name: Download the versioned release artifact from S3
   #     aws_s3:
   #       bucket: "{{ s3_bucket_releases }}"
   #       object: "chl-perl/{{ application_name }}/{{ application_name }}-{{ version }}.zip"
   #       dest: "/tmp/{{ application_name }}-{{ version }}.zip"
   #       mode: get

   #   - name: Create temporary app folder for unzip
   #     file:
   #       path: "/tmp/{{ application_name }}-{{ version }}"
   #       state: directory

      - name: Make sure config directory exists
        file:
          path: "{{ home_dir }}/config/My"
          state: directory
          recurse: yes
          mode: '0755'

      - name: Download environment config files from S3
        aws_s3:
          bucket: "{{ s3_bucket_configs }}"
          object: "chl-{{ application_name }}-configs/{{ heritage_environment }}/{{ item | upper }}.properties"
          dest: "{{ home_dir }}/config/My/{{ item | upper }}.properties"
          mode: get
        loop: "{{ config_files }}"

      - name: Change config owners and permission
        ansible.builtin.file:
          path: "{{ home_dir }}/config/My/{{ item | upper }}.properties"
          owner: "{{ home_dir | basename }}"
          group: chlservices
          mode: '0755'
        loop: "{{ config_files }}"
        